### PR TITLE
rename libRmath to libRmathjulia

### LINKED ISSUE #13: using the wrong libRmath instead of libRmath-julia
I already have a "/usr/local/lib/libRmath.dylib". `Pkg.build("Rmath")` does not install Rmath-julia at all.
~~~julia
julia> Pkg.build("Rmath")
INFO: Building Rmath
julia> using Rmath
julia> import Rmath: libRmath
julia> libRmath
"/usr/local/lib/libRmath.dylib"
~~~
This file points to the libRmath in R
`libRmath.dylib -> ../Cellar/r/3.3.1_2/lib/libRmath.dylib`

Since it is linking to the wrong Rmath, `srand(100)` cannot fix the random number
~~~julia
julia> srand(100); Rmath.rpois(2,55)
2-element Array{Float64,1}:
 45.0
 47.0

julia> srand(100); Rmath.rpois(2,55)
2-element Array{Float64,1}:
 52.0
 67.0
~~~

If I remove this file, the following lib will be linked
"/Users/lanfengpan/julia/lib/julia/libRmath-julia.dylib"
This time `srand` works but not sure this is the right one because the `deps.jl` tries to install it into `.julia/deps/usr/lib` instead.

So probably we should rename the library `libRmath` to be something else in `deps.jl` to avoid using existing library? Many people already have some kind of Rmath installed. 

Both `Distributions` and `StatsFuns` are effected.

### PR DESCRIPTION
**Pull request by panlanfeng**
Minimize the changes to fix #13.

### CODE REVIEW

**Comment by tkelman** [comment]
please add a test for #13

**Comment by tkelman** [comment]
oh right, they're in #14, sorry

**Comment by panlanfeng** [comment]
Just realized there is no need to edit `src/Rmath.jl` file.

**Comment by ararslan** [comment]
I have a feeling this will cause some issues with stats packages that call directly into the library rather than using the Julia functions in this package. I don't think too many of them do but I'll keep an eye out for any "halp where did rmath go" errors.

**Comment by tkelman** [comment]
This version of the change should be entirely localized to the action of the build.jl script, making it less likely to pick up an existing libRmath from the system. But maybe there are cases where that was happening and it was helping more than hurting, in which case keeping an eye out is warranted.

**Comment by panlanfeng** [comment]
The true name of the library is "libRmath-julia.$(Libdl.dlext)" but dash is not allowed in `Symbol`. So we need to give it a nickname.
It doesn't matter if we give it any other nickname "libfoo" or "libthename" as long as it doesn't cause confusing with system library.

**Comment by ararslan** [comment]
Ah yes, sorry, I missed that. Thank you both for correcting me, and thanks to Lanfeng for the contribution!

**Pull request merged**
