### PR TITLE
Add dSFMT.h code and their license; build Rmath with dSFMT

### PR DESCRIPTION
**Pull request by panlanfeng**
Add dSFMT.h file and its license under `deps`. Build Rmath with dSFMT to enable `srand`.

### CODE REVIEW

**Comment by panlanfeng** [comment]
Not sure if I treat the license file in the right way. Anyone gives some feedback?
After building Rmath against dSFMT, `srand` will work on Julia 0.5 and #14 will also pass the checks.

**Comment by tkelman** [comment]
looks okay to me

**Comment by ararslan** [comment]
Is there a way that dSFMT can be automatically fetched from somewhere, like BinDeps usually does, rather than including the source directly? That would make maintenance easier if it's possible. If not, this looks okay to me as well.

**Comment by tkelman** [comment]
You'd also have to fetch and apply the patch. It's been 3 years since the last release... http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/SFMT/

**Comment by ararslan** [comment]
Wow, not particularly observant today, am I? Missed that entire thread.

**Pull request merged**
