### PR TITLE
build Rmath against dSFMT to enable `srand`

### PR DESCRIPTION
**Pull request by panlanfeng**
This pull request will not working automatically unless julia ships with the file "dSFMT.h".
Right now we need to manually link the file, or copy the file "dSFMT.h" to a folder such as 
~~~julia
normpath(joinpath(ENV["_"], "../..", "include/julia/"))
~~~
This file can be found at `usr/include` if julia is built from source. 

Julia v0.4 ships with the correct `libRmath`, so it works automatically. 

Let me know if there is some other plan or there is better ideas.

### CODE REVIEW

**Comment by tkelman** [comment]
This won't work in a binary install of julia. How badly do you need the rmath functions to be tied to Julia's rng?

**Comment by nalimilan** [comment]
> How badly do you need the rmath functions to be tied to Julia's rng?

One the the major uses cases I can see is getting reproducible results for testing.

Maybe we could download and build dSFMT? It's relatively small and fast to compile.

**Comment by tkelman** [comment]
Or just check in a copy here under deps, either way.

**Comment by panlanfeng** [comment]
Badly needed and urgent.
Just about to submit a paper (in Statistics) and found all my previous result cannot be reproduced.
We have hundreds of simulated data and it took days to fit each of them.

**Comment by tkelman** [comment]
This shouldn't have changed anything on 0.4.

**Comment by panlanfeng** [comment]
Yes if we fixed #13 .
But I hope to safely transfer to v0.5. It can one year for referees to review and give feedback.

**Comment by tkelman** [comment]
You can pin to older package versions if you need to reproduce results right now.

I'd advise adding tests for the functionality you find important, otherwise it can easily stop working and no one will notice.

**Comment by panlanfeng** [comment]
Right now it downloads the dSFMT.h file and can build automatically.

**Comment by tkelman** [comment]
Julia's version of dsfmt has several patches applied. Those may be important here.

**Comment by panlanfeng** [comment]
The build process of dsfmt does not actually run since "libdSFMT" can be found together with other libraries from Julia.
The build process is from this [file](https://github.com/JuliaLang/julia/blob/master/deps/dsfmt.mk).
The differences are `CC` is set to be `gcc` and `fPIC` is not used.

**Comment by tkelman** [comment]
The patch changes the content of the header too, which matters here.

**Comment by panlanfeng** [comment]
I see.
What is  best way to this? 
Can I upload my local patched "dSFMT.h" to a github repository and then download it?

**Comment by tkelman** [comment]
or just commit it here under deps and add it to thr license file, then no need to worry about downloading anything

**Comment by panlanfeng** [comment]
See #18

**Pull request closed without merging**
